version: '3'

services:
  api:
    image: jwbaldwin/flowist
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - main
    deploy:
      restart_policy:
        condition: on_failure
        delay: 10s
        max_attempts: 3
  backend:
    image: jwbaldwin/flowist-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - main
    deploy:
      restart_policy:
        condition: on_failure
        delay: 10s
        max_attempts: 3
networks:
  main:
