version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    depends_on:
      - api
      - frontend

  api:
    image: jwbaldwin/flowist
    expose:
      - 8080
    networks:
      - main
    restart: always

  frontend:
    image: jwbaldwin/flowist-frontend
    expose:
      - 3000
    networks:
      - main
    restart: always

networks:
  main:
