# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: .

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # git pull
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

    # run tests!
    - run: ./gradlew test
      if [[ -z "${DOCKER_PASSWORD}" ]]; then
      echo "DOCKER_PASSWORD is not set, will not be able to push image."
      exit 1
      fi
    - run:
        name: Docker Login
        command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" docker.io
    - run:
        name: Build Docker Image
        command: |
          docker build \
             \
            -f Dockerfile -t \
            docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
            .
    - run:
        name: Push Docker Image
        command: |
          if [[ $CIRCLE_NODE_INDEX == 0 ]]; then
            docker push docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          fi
workflows:
  build-test-deploy:
    jobs:
      - test-build
      - docker-publish:
          requires:
            - test-build
          filters:
            branches:
              only: master
