# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  gradle: circleci/gradle@1.0.11
  docker-publish: circleci/docker-publish@0.1.6
workflows:
  build-test-deploy:
    jobs:
      - gradle/test:
          test_command: test
          test_results_path: build/test-results/test/*.xml
          reports_path: ~/reports
      - gradle/run:
          command: build
      - docker-publish/publish:
          requires:
            - gradle/test
            - gradle/run