# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  gradle: circleci/gradle@1.0.0
workflows:
  test-with-custom-reports:
    jobs:
      - gradle/test
        test_results_path: build/test-results/test/
        store_artifacts: build/test-results/test/